### PR TITLE
Add "Delivered to storage" to Statistics

### PR DESCRIPTION
**Pull request by isaisstillalive**
Even with the same shape, it is recorded for each storage.
PR_delivered_to_storage

### CODE REVIEW

**Comment by tobspr** [comment]
Hey! I appreciate this, but wouldn't it make more sense to show this information when hovering it?

**Comment by isaisstillalive** [comment]
Yes, I would like this information to be displayed when hovering.
But I didn't understand the standard hover information UI, so I tried displaying it on the Statistics screen.

**Comment by tobspr** [comment]
Okay, well I would like to avoid a new category, so it'd be nice to have it as tooltip instead ..

**Comment by isaisstillalive** [comment]
@tobspr 
How about switching between quantity and throughput with a click of storage?
storage_display_throughput

**Comment by tobspr** [comment]
Ah! Yeah thats a cool idea. Looks good, will try to merge soon

**Comment by tobspr** [comment]
I will add a belt reader building soon, which will make this obsolete - Otherwise there would be two ways to measure belt speed

**Pull request closed without merging**
