### PR TITLE
Add linux build to standalone building process

### PR DESCRIPTION
**Pull request by hexagonhexagon**
Add a linux build. Not much more to it than that.

### CODE REVIEW

**Comment by tobspr** [comment]
Have you tried it on a linux system? Since for me it doesn't seem to work

**Comment by hexagonhexagon** [comment]
I use this branch to build standalone for Linux on my Ubuntu machine, so it definitely works for me. What do you mean when you say it doesn't work for you?

**Comment by tobspr** [comment]
dengr tested it, but I guess I should offer experimental mac osx and linux builds

**Comment by tobspr** [comment]
I just added experimental builds

**Pull request closed without merging**
