### PR TITLE
Update base-fr.yaml

### PR DESCRIPTION
**Pull request by tonitch**

### CODE REVIEW

**Comment by tobspr** [comment]
Cool, thanks!

**Comment by JeremyMeissner** [comment]
Be careful, in French there is a space before each punctuation.
`Hello!` become `Bonjour !`

**Comment by tonitch** [comment]
yhea, sorry! I'm from belgium and I have learned typing with my software
teacher who told us to link word with punctuation
btw I haven't finished it yet... I just had to go and saved it for other to
take the lead or for me to finish later


Le ven. 4 juin 2021 à 11:54, Jeremy Meissner ***@***.***> a
écrit :

**Comment by JeremyMeissner** [comment]
No problem, I've open another pull request to fix that #1187
I found [an article](https://www.blogdumoderateur.com/regles-ponctuation-typographie/) that can help you with that if you want! Have a nice day 😉

**Pull request merged**
