### PR TITLE
Make numbers display to set amount of significant figures

### PR DESCRIPTION
**Pull request by EmeraldBlock**
This modifies the formatBigNumber function so that it outputs numbers to a set amount of significant figures (default of 3). It also has a new optional argument for the number of significant figures.

The hub delivered text size is also made smaller (16px starting from 1000 instead of 10000) to accommodate the additional digit.

image
image

This is my first PR ever, and I tested it through an unorthodox method, so there may be some issues.

### CODE REVIEW

**Comment by EmeraldBlock** [comment]
The number's length sort of "pulses" whenever it hits a rounder number, it might be better to display trailing zeroes, but not sure

**Comment by tobspr** [comment]
Hm I'll need to test it first, on my todo list

**Comment by EmeraldBlock** [comment]
oops, committed something to the wrong branch

**Comment by tobspr** [comment]
Not planning to merge right now, thus closing - I don't see the benefit currently

**Pull request closed without merging**
