### PR TITLE
Update gulp to version 4

### PR DESCRIPTION
**Pull request by Demivan**
I wanted to play around with the project but did not want to downgrade my Node. So I just switched it to gulp 4.

Tested most of the tasks. Did not test ftp tasks and build on systems other then Linux.
Did not remove `gulp-multi-process` usages. Was not sure why it was used. Usages can probably be changed to `gulp.parallel`
Did not change Travis config. It is possible to build project on Node.js other then version 10 (I'm using version 14)

### CODE REVIEW

**Comment by tobspr** [comment]
Ah nice! Thats pretty cool. I always planned that but was afraid to update the code

**Comment by Demivan** [comment]
I was postponing switch to gulp 4 on my work project too. But after we needed to upgrade Node I was forced to. It was surprisingly painless.
Should I switch from `gulp-multi-process` to build-in `gulp.parallel`?
And should I update Travis config to use newer Node?

**Comment by Demivan** [comment]
Just tested `gulp.parallel` and build is a little bit faster with it. Removed `gulp-multi-process`

**Comment by Demivan** [comment]
Fixed build on Windows. Pull request is ready for review.

**Comment by daiyam** [comment]
This comment isn't about the PR ;)

@Demivan You should check [nvm](https://github.com/nvm-sh/nvm) which allows you to have multiple versions of nodejs.

**Comment by tobspr** [comment]
Will definitely get to it. Just too busy right now. But it has been on my todo list for ages - kudos.

**Comment by dengr1065** [comment]
nvm sucks on linux, and i think, also on windows. i use portable copy of node.js and that works, but node 10 sucks anyway - it lacks many (really many) features of ecmascript, like multiple object attribute setting and other things like that

@tobspr do it asap, it's cool and it could be merged to a separate experimental branch

**Comment by tobspr** [comment]
Tested and works, huge thanks!

**Pull request merged**
