### PR TITLE
Free Texture packing workflow.

### PR DESCRIPTION
**Pull request by theisen1337**
This allows for an alternate workflow for texture and loading textures into the atlas allowing for more users to create more content for the game.

### CODE REVIEW

**Comment by theisen1337** [comment]
This will allow great advances in user create content for the game.

**Comment by tobspr** [comment]
I appreciate the work - But actually I would prefer a more battle tested solution. @dengr1065 Wanted to look into GDX Texture Packager afaik. I feel like having one definite workflow would be better

**Comment by theisen1337** [comment]
Well I really wish you would have send something before I spent all that time on it. perfecting all the sprites settings with the text packer, only took me like 14 hours. It doesn't replace any of the textures by default. It needs to be manually ran than the project needs to be rebuilt..

**Comment by tobspr** [comment]
Closing this for now

**Pull request closed without merging**
