### PR TITLE
Chainable balancer

### PR DESCRIPTION
**Pull request by isaisstillalive**
The side-by-side balancers are concatenated to output the inputs evenly.
PR_chainable_balancer1

You can split the output into prime numbers.
PR_chainable_balancer3

If one output is clogged, the same number will be output and all will stop.
PR_chainable_balancer2

### CODE REVIEW

**Comment by isaisstillalive** [comment]
Changed to not stall.
It seemed more convenient.
PR_chainable_balancer4

**Comment by isaisstillalive** [comment]
If you line up a lot of them, there is a problem that they can be transported in a moment in the distance.
I plan to add the concept of distance.

PR_chainable_balancer5

**Comment by isaisstillalive** [comment]
The distant objects are delayed and output according to the belt speed.
Priority is given to the output slot near the input slot.
In essence, the behavior now matches the look and feel.
PR_chainable_balancer6

**Comment by tobspr** [comment]
Hey,

I currently don't plan on adding this building :) If you plan on buildings to get merged, please reach out to me first :)

**Pull request closed without merging**
