### PR TITLE
Symmetric piece generator

### PR DESCRIPTION
**Pull request by chocoman**

### CODE REVIEW

**Comment by chocoman** [comment]
Travis failed, but it is likely not an issue with this branch, because master fails with the same errors.

**Comment by tobspr** [comment]
Uhm .. could you give a bit more context?

**Comment by chocoman** [comment]
this merge request is an implementation of the suggestion that I had on discord yesterday:

> Suggestion: better looking random shapes for levels 19+. Frankly, the generated shapes are quite ugly, compared to the shapes in previous levels. Producing them correctly feels less rewarding than with the better looking shapes in previous levels.
I think that forcing symmetry (radial or along vertical, horizontal or diagonal axis) might help. Also colors could be picked so that they aesthetically fit together. I would be interested in implementing that, I guess it could be very straight-forward. Shall I do that? Or are there other plans for the late-game levels?

pictures of the shapes generated by the new generator are in
https://github.com/tobspr/shapez.io/issues/391

**Comment by tobspr** [comment]
I'll have a look!

**Comment by BaleineSanguine** [comment]
Looks like a good idea, can you give some screenshots to see the difference ?

**Comment by tobspr** [comment]
This looks cool and is on my todo list

**Comment by chocoman** [comment]
These shapes were automatically generated by this code. See that pieces are either symmetric along vertical, horizontal or diagonal axis, or they are rotationally symmetric. Each piece uses only a small set of colors that fit together.
shapes_generator

**Comment by Dimava** [comment]
I think you should switch from random generation to seeded-random generation based on world seed and target level
See map generation for samples

**Comment by chocoman** [comment]
> I think you should switch from random generation to seeded-random generation based on world seed and target level
> See map generation for samples

Ok, I can do that

**Comment by tobspr** [comment]
Merged with https://github.com/tobspr/shapez.io/commit/4f6d9785c16e83816233be24b427df17fc6ca2f6

**Pull request closed without merging**
