### PR TITLE
All polish translations done!

### PR DESCRIPTION
**Pull request by Norbiros**
A lot of new updates and tweaks to Polish translations.
Now all translations are done!

### CODE REVIEW

**Comment by Norbiros** [comment]
@tobspr can you please help me with that? 
I don't know how to fix this error...

**Comment by DerFeldspatz** [comment]
Your error is:
```
translations/base-pl.yaml
  79:82     error    trailing spaces  (trailing-spaces)
  236:94    error    trailing spaces  (trailing-spaces)
  248:43    error    trailing spaces  (trailing-spaces)
  1275:73   error    trailing spaces  (trailing-spaces)
  1331:76   error    trailing spaces  (trailing-spaces)
  ```
The first error means that in line 79 on position 82 there are trailing spaces (spaces after the last character). Same goes for the other error messages respectively.
Just delete the spaces after the last character and you are fine.

**Comment by DerFeldspatz** [comment]
The remaining errors are none of your business. Kind of... x)
They are caused by other contributors so no need to worry

**Comment by Norbiros** [comment]
Oh okay :)

**Pull request merged**
