### PR TITLE
gitignore update

### PR DESCRIPTION
**Pull request by ModdedGamers**
Updates .gitignore so git push won't complain about workflow files on cli.

### CODE REVIEW

**Comment by tobspr** [comment]
I don't think thats a good idea - Why do you want to add it to the gitignore?

**Comment by ModdedGamers** [comment]
Because if you have a Github api token, and it doesn't have the workflows permission, You can't push without removing the file from git anyways. This just makes it easier to push without having to remember to remove the file. Plus, people will almost always work on the workflow files on the github website. So, not tracking these on remote machines is a better idea to create less hassle.

**Comment by tobspr** [comment]
But shouldn't you be able to just work in your local repository?

**Comment by ModdedGamers** [comment]
Even if you don't change the file, github won't let you push without explicitly removing it from git's index.

**Comment by tobspr** [comment]
Thats weird, but I'll just accept it then I guess

**Pull request merged**
