### PR TITLE
Update base-de.yaml

### PR DESCRIPTION
**Pull request by DerFeldspatz**
Typos, Grammar, concistency of punctuation and `drück(e)`. Some phrasing and a suggestion for the translation of new volume feature. @Yoshie2000 please check if it's ok :) 
Feedback and reviews appreciated.

### CODE REVIEW

**Comment by Yoshie2000** [comment]
This is fine with me, I like this translation a lot better than my original one.
I'm not quite sure if we should replace `drücke` with `drück`. Technically both is correct, I personally prefer `drücke`, but I don't mind it being `drück` either...

**Comment by DerFeldspatz** [comment]
I had to start somewhere 😅

**Comment by DerFeldspatz** [comment]
It's changed to `Drücke` now consisently.

**Comment by tobspr** [comment]
Vielen Dank!

**Pull request merged**
