### PR TITLE
Fix blueprint bugs, take 2: electric boogaloo

### PR DESCRIPTION
**Pull request by hexagonhexagon**
Apparently the first time I tried this, it didn't cover all the necessary cases, so I have taken a different approach and decided to make it so that `updateSurroundingBeltPlacement()` is only called when belts are manually placed rather than when any entity is placed, and if they are placed by blueprint then only the belt cache is updated for that area.

I have also fixed another bug that was described in the discord where the belt blueprint preview didn't match the thing you were copying.

test

### CODE REVIEW

**Comment by hexagonhexagon** [comment]
This has been updated to work with the new belt changes.

**Comment by kubiix** [comment]
Please can you check if this case is solved too ?

obrazek

obrazek

obrazek

**Comment by hexagonhexagon** [comment]
Looks like this fix solves that case.

test

**Comment by kubiix** [comment]
Found one more to test

obrazek

**Comment by tobspr** [comment]
Cool! I'll try to get to it shortly, but notice that it might be broken with the wires changes :D

**Comment by hexagonhexagon** [comment]
T\_T

**Comment by tobspr** [comment]
@hexagonhexagon this should be much easier now since the building code is now stored. Should I just close it though?

**Comment by tobspr** [comment]
Outdated, also I won't fix this since it causes other issues (Even if the belt look exactly like the blueprint after placed, this removes the ability to update existing belts)

**Pull request closed without merging**
