### PR TITLE
Updated hub.png

### PR DESCRIPTION
**Pull request by derekShaheen**
- Corrected the misaligned corners by following the natural angles.

### CODE REVIEW

**Comment by EmeraldBlock** [comment]
the hub is meant to look like that

**Comment by derekShaheen** [comment]
Really? It's listed under the bugs section on the Trello, but not sure if that is updated anymore.

https://trello.com/c/yUiNmr5w/492-imagepng

**Comment by EmeraldBlock** [comment]
that's the fault of the belt, not the hub

**Comment by tobspr** [comment]
ugh, don't really like the rectangular shape

**Comment by derekShaheen** [comment]
That is honestly super fair, it does seem kinda strange, doesn't it?

**Pull request closed without merging**
