### PR TITLE
Minor English Adjustments

### PR DESCRIPTION
**Pull request by TrapperHell**
- Minor adjustments in English translation of game and adjust casing of product names
- Fix comment typo

### CODE REVIEW

**Comment by TrapperHell** [comment]
I would have also liked to make a small adjustment here:

image

but I can't seem to find it in the source code. The better way to end the sentence is _where you left off_

**Review by kedihacker — CHANGES_REQUESTED** [review]
u dont need to write google chrome just write Chrome everybody know it

**Comment by Serenata-Justin** [comment]
Sure everyone would know, but the official name of the product is Google Chrome - might as well be formal with it.

**Comment by TrapperHell** [comment]
Sure everyone would know, but the official name of the product is Google Chrome - might as well be formal with it.

**Comment by kedihacker** [comment]
did we are a big game company?

**Comment by TrapperHell** [comment]
Did I say that it's a big game company? I don't see how that makes any difference.

**Comment by kedihacker** [comment]
its more frindly

**Comment by kedihacker** [comment]
ist just shorter

**Review by kedihacker — APPROVED** [review]
its enough

**Comment by tobspr** [comment]
> but I can't seem to find it in the source code. 

That's because its in a different branch :)

**Comment by tobspr** [comment]
Ty!

**Pull request merged**
