### PR TITLE
WIP: undo / redo commands (entity placement)

### PR DESCRIPTION
**Pull request by akupiec**
Currently working:
 - redo/undo can store up to 20 events
 - Ctrl+Z to undo last block placement / last block removal
 - ~Ctrl+Shift+Z~ Ctrl+Y to redo last undo
 
 TODO:
 - lock history until ?? level
 - localize and fix save corruptions - related to bulk operations
 - ~~add HUD info~~
 - ~~add possibility to bulk undo operation (paste/remove)~~
 - ~~reduce memory footprint & performance test~~

### CODE REVIEW

**Comment by darkwater4213** [comment]
> Ctrl+Shift+Z to redo last undo

Possibly replace with Ctrl+Y? That tends to be the default "redo" keyboard shortcut.
Otherwise, I really like this idea and would not complain if it were in the next update!

**Comment by tobspr** [comment]
If I may give a suggestion, I would make the actions a class and every action derives from it :)

**Comment by akupiec** [comment]
> Possibly replace with Ctrl+Y? 
Done :) 

I'm still struggling with bulk undo/redo

**Comment by tobspr** [comment]
Not planning to put this into the base game right now, but with the 1.5.0 update it could be a mod. Closing to clean up PR's a bit.

**Comment by brignano** [comment]
@tobspr - I would also like to have undo / redo added to `shapez.io` (I was planning to raise a pull request for it) but you mentioned,

> Not planning to put this into the base game right now,

Should we move [Undo / Redo on shapez - Development Board | Trello](https://trello.com/c/Dp7kIfAW/304-undo-redo) from `FEATURE SUGGESTIONS` to `Won't be implemented - But could be/is a mod` then?

**Pull request closed without merging**
