### PR TITLE
Ability to edit Constant Signals

### PR DESCRIPTION
**Pull request by Git-Nivrak**

### CODE REVIEW

**Comment by tobspr** [comment]
Can you have a look at the linter issues first? :)

**Comment by daanbreur** [comment]
May I take a look at this??

**Comment by Git-Nivrak** [comment]
Are the YAML lint errors an issue too?

**Comment by daanbreur** [comment]
No.

**Comment by tobspr** [comment]
Uh so, I don't really like storing a `clicked` flag on the constant signal.

Instead, why not call `this.root.systemMgr.systems.constantSignal.triggerSignalEdit()`? 

Actually the clean way (Which I failed my self to do and I can fix too :P) would be to have the whole editing of the constant signal within a HUD component and have the HUD component listen on that.

Let me know if you want to do it or I should do it

**Comment by Git-Nivrak** [comment]
^ Like so?

**Comment by tobspr** [comment]
Similar, since the creation and editing of constant signals is the same, I think the code should be shared

**Comment by Git-Nivrak** [comment]
Not exactly the same, You don't want it to destroy the object when they press cancel once it is already placed

**Comment by Git-Nivrak** [comment]
Maybe I'll add an optional argument for if it is editing or creating

**Comment by daanbreur** [comment]
@tobspr is right. The code should be shared

**Comment by Git-Nivrak** [comment]
Here

**Comment by tobspr** [comment]
I recommend to install eslint and prettier, there are a lot of linter issues again ! :) :P

**Comment by Git-Nivrak** [comment]
I have them downloaded, I thought the lint YAML wasn't an Issue?

**Comment by tobspr** [comment]
No, not YAML, but seee the github comments :)

**Comment by tobspr** [comment]
Looks good now! Probably won't make it into the wires update though, depends on how much time I have left

**Comment by Git-Nivrak** [comment]
Soon™

**Comment by tobspr** [comment]
Sooner™

**Comment by Git-Nivrak** [comment]
Soonest™

**Comment by darkwater4213** [comment]
Yay! I like this idea too.

**Comment by tobspr** [comment]
Done in 1.2.2

**Pull request closed without merging**
