### PR TITLE
Merge base-*.yaml & fix YAML lint errors and warnings.

### PR DESCRIPTION
**Pull request by AdJaGu**
**Merged**:

1. #837 base-ind.yaml
2. #838 base-cz.yaml
3. #840 base-zh-TW.yaml
4. #861 base-uk.yaml
5. #863 base-pl.yaml
6. #864 base-fi.yaml
7. #876 base-ja.yaml
8. #884 base-kor.yaml
9. #898 base-it.yaml
10. #903 base-sv.yaml
11. #906 base-en.yaml
12. #913 base-ro.yaml

**Fixed remaining YAML lint errors and warnings**:
_translations/base-ar.yaml_
  `9:201     warning  line too long (226 > 200 characters)  (line-length)`

_translations/base-da.yaml_
  `995:201   warning  line too long (204 > 200 characters)  (line-length)`

_translations/base-de.yaml_
  `10:201    warning  line too long (254 > 200 characters)  (line-length)`
  `12:201    warning  line too long (294 > 200 characters)  (line-length)`

_translations/base-en.yaml_
  `33:201    warning  line too long (235 > 200 characters)  (line-length)`
  `35:201    warning  line too long (269 > 200 characters)  (line-length)`
  `405:201   warning  line too long (226 > 200 characters)  (line-length)`
  `423:201   warning  line too long (231 > 200 characters)  (line-length)`
  `732:201   warning  line too long (353 > 200 characters)  (line-length)`
  `741:201   warning  line too long (267 > 200 characters)  (line-length)`
  `749:201   warning  line too long (259 > 200 characters)  (line-length)`
  `761:201   warning  line too long (219 > 200 characters)  (line-length)`
  `794:201   warning  line too long (207 > 200 characters)  (line-length)`
  `804:201   warning  line too long (305 > 200 characters)  (line-length)`
  `860:201   warning  line too long (210 > 200 characters)  (line-length)`
  `989:201   warning  line too long (205 > 200 characters)  (line-length)`
  `1040:201  warning  line too long (210 > 200 characters)  (line-length)`

_translations/base-fr.yaml_
  `9:201     warning  line too long (258 > 200 characters)  (line-length)`
  `11:201    warning  line too long (290 > 200 characters)  (line-length)`
  `1031:201  warning  line too long (206 > 200 characters)  (line-length)`

_translations/base-ind.yaml_
  `9:201     warning  line too long (247 > 200 characters)  (line-length)`
  `11:201    warning  line too long (295 > 200 characters)  (line-length)`
  `904:201   warning  line too long (257 > 200 characters)  (line-length)`
  `1019:201  warning  line too long (201 > 200 characters)  (line-length)`

_translations/base-ja.yaml_
  `595:201   warning  line too long (206 > 200 characters)  (line-length)`

_translations/base-nl.yaml_
  `319:79    error    trailing spaces  (trailing-spaces)`
  `1004:201  warning  line too long (221 > 200 characters)  (line-length)`

_translations/base-ro.yaml_
  `1007:201  warning  line too long (209 > 200 characters)  (line-length)`

_translations/base-ru.yaml_
  `1000:201  warning  line too long (219 > 200 characters)  (line-length)`

### CODE REVIEW

**Comment by Hyperion-21** [comment]
cool

**Comment by presdm** [comment]
nice!

**Comment by Colleabois** [comment]
Thanks!

**Comment by tobspr** [comment]
Wow, thanks a lot!

**Pull request merged**
