### PR TITLE
Fix YAML Lint Failures

### PR DESCRIPTION
**Pull request by bjornstar**
First step was copy/pasting `base-en` onto `base-ar`. I couldn't find a single translated entry.

### CODE REVIEW

**Comment by bjornstar** [comment]
I was a bit confused by the CI messages, I didn't realize there was a scrollbar in that area and started fixing warnings instead.

#546 will fix CI, up to you what you want to do.

**Comment by tobspr** [comment]
Ty! There is a conflict tho (Due to a PR I just merged) - Could you have a look? :)

**Comment by bjornstar** [comment]
This sure does break a lot.

Fixed again.

**Comment by tobspr** [comment]
Ty!

**Pull request merged**
