### PR TITLE
Fix Yaml errors and lint problems

### PR DESCRIPTION
**Pull request by KaiSforza**
Fixes the issues present in #767, #775, #765.

### CODE REVIEW

**Comment by tobspr** [comment]
thanks! Actually I fixed most of these issues already :P Are there some I missed?

**Comment by KaiSforza** [comment]
not sure, let me check.

**Comment by KaiSforza** [comment]
Just one change, this is just removing some extra spaces.

**Comment by tobspr** [comment]
Perfect, thank you! :)

**Pull request merged**
