### PR TITLE
L1-100 translated

### PR DESCRIPTION
**Pull request by ananbaobeichicun**
I'm only free at the weekend. So it's convenient for me to request more times with less content.
I'll pull a request for every 100 lines translated.

### CODE REVIEW

**Comment by findaldudu** [comment]
I made a full translation here.
https://github.com/tobspr/shapez.io/pull/219
It needs a lot of refinement. Feel free to edit there, or merge ours together.

**Comment by ananbaobeichicun** [comment]
Let's merge ours together. You did pretty well.
May I pull requests to your repository directly from now on?

**Comment by findaldudu** [comment]
Sure. Go ahead. I'll review them shortly.

**Comment by ananbaobeichicun** [comment]
But how to merge two forked repository?

**Comment by tobspr** [comment]
I merged #219 - Should this still be merged?

**Comment by findaldudu** [comment]
This pull request seems to be the same as https://github.com/tobspr/shapez.io/pull/219
Maybe it's some merge error.
I made a new [pull request](https://github.com/tobspr/shapez.io/pull/243) including commit 25957c8 in this pull request. We can use that instead.

**Pull request closed without merging**
