### PR TITLE
Build, sign, notarise, & upload on OS X

### PR DESCRIPTION
**Pull request by LeopoldTal**
# What's it do

* `standalone.package.prod.darwin64` now signs and notarises the build
* New task `standalone.package.prod.darwin64.unsigned` to skip signing (useful for test snapshots)
* New task `standalone.uploadRelease.darwin64` creates a github release with the build for the checked-out tag. The release is marked as draft so it won't be public.
* New task `build.darwin64-prod` to do it all in one step

@tobspr I've given you write rights to my fork so you can grab the [releases](https://github.com/LeopoldTal/shapez.io/releases). They're dmgs, if you want tarballs or something that's a trivial change.

The result of all that is that when the user opens the app… there's still a Gatekeeper warning, but with tiny fine print about not finding any malware. Success?

Notarisation takes *forever*, limited mostly by uplink speed.

# Prereqs

I don't really expect this will run anywhere but my own machine, because there's enormous ceremony.

## Apple stuff

* An Apple Developer ID (€99/year, legal name, address, phone number, and sacrificing your firstborn to Tim Cook), with the Apple ID in env var `SHAPEZ_CLI_APPLE_ID`
* A Developer ID Application certificate
  * Cert name in env var `SHAPEZ_CLI_APPLE_CERT_NAME`
  * Cert itself in keychain
* An application-specific password in keychain named `SHAPEZ_CLI_APPLE_ID`
* XCode

## Github stuff

* Github username in env var `SHAPEZ_CLI_GITHUB_USER`
* [Personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with (public) repo access in env var `SHAPEZ_CLI_GITHUB_TOKEN`

# Now what?

You can push the builds to Steam and itch.io. For now I'm planning to build manually since releases are infrequent.

I don't really want to pay €99 every year to Apple blackmail, would appreciate if you chipped in next year and following.

If you want to own the whole build chain, I'll hand over the credentials, but I don't know how you'll do it without Apple hardware. Abusing github actions? Mac cloud services?

### CODE REVIEW

**Comment by izanagi1995** [comment]
Nice work ! Thanks for the OSX build 👍 LGTM

**Comment by tobspr** [comment]
Really awesome, thanks a lot!

**Comment by tobspr** [comment]
Also this is a good PR to link to when somebody asks why there are no OSX builds yet ...

**Comment by jirir** [comment]
I've purchased the game on Steam. Please make the macOS version :) Thanks.

**Comment by dacoinminster** [comment]
I will buy on steam once MacOS version is available!

**Comment by pinzonjulian** [comment]
> I will buy on steam once MacOS version is available!

same!

**Comment by robert2411** [comment]
Wouldn't it be possible to build the osx with GitHub actions: 
https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/

**Comment by joshuaflanagan** [comment]
> Also this is a good PR to link to when somebody asks why there are no OSX builds yet ...

Anyone that was linked here should know that most of the work in this PR was reverted by https://github.com/tobspr/shapez.io/commit/1ee03d739846636f7bc67d5430ee1dddc10de628

**Pull request merged**
