### PR TITLE
Fix building placer checking on wrong layer for acceptors and ejectors

### PR DESCRIPTION
**Pull request by Sense101**
Simple fix, just checks on the layer of the current fake entity.

### CODE REVIEW

**Comment by dengr1065** [comment]
duplicate of #1035?

**Comment by Sense101** [comment]
... at least it helps it get noticed lol

**Comment by EmeraldBlock** [comment]
my PR has comments >:)

...and actually does what it claims to do ;)

**Comment by Sense101** [comment]
Oh alright then :(

**Pull request closed without merging**
