### PR TITLE
inject KeybindingsState into SettingsState

### PR DESCRIPTION
**Pull request by Dimava**

### CODE REVIEW

**Comment by tobspr** [comment]
What does this do? Show keybindings on the settings page?

**Comment by Dimava** [comment]
This seamlessly integrates Keybindings screen into Settings screen
image

**Comment by Dimava** [comment]
You may check keybing settings on https://dimava.github.io/shapez/modZ/ to see how that looks on live.

**Comment by tobspr** [comment]
You are not changing into the "new" settings state though, so this will error, not?

**Comment by Dimava** [comment]
I replace Settings state with combined state (made as KeybindingsState extends SettingsState).
So instead of Setting state there is the Settings (+keybindings) state where both pieces are on at once.
It enables both of their interactivity, and sharing their html space
Html makes one shared element, with one of its children made for inserting other settings and another child for inserting keybindings

**Comment by Dimava** [comment]
The new state is still called "settings" and completely replaces old "settings" state so that does not causes errors
As for "does it work" you may check https://dimava.github.io/shapez/modZ/ where it does work perfectly

**Comment by tobspr** [comment]
Hm, I like the idea, but I think instead I should refactor the settings state since this solution is kinda hacky and I don't like that

**Comment by tobspr** [comment]
Closing since for merging, it would first have to get refactored

**Pull request closed without merging**
