### PR TITLE
Achievements ingame

### PR DESCRIPTION
**Pull request by DJ1TJOO**
### Added
- Achievement viewer
- Achievement support for browser (dev only)
- Achievement storage for browser
- Achievement resetting
- Hidden achievements not shown

achievements

### CODE REVIEW

**Comment by tobspr** [comment]
Can't really review it due to all the formatting changes :/

**Comment by tobspr** [comment]
Had a quick look at the code, looks good to me. But I didn't get to test it

**Comment by EmeraldBlock** [comment]
I feel maybe adding an achievements button to the main menu would be nice (since they are tied to game)? Also, when I opened a save some achievements showed an unlock dialog multiple times - maybe they were triggered multiple times simultaneously?

**Comment by DJ1TJOO** [comment]
I've added the reset all button and fixed the double notifications
Achievements

**Comment by DJ1TJOO** [comment]
Added achievements to the main menu
Achievements icon
Achievements

**Comment by DJ1TJOO** [comment]
> Added achievements to the main menu
> Achievements icon
> Achievements

Reset buttons are removed. Not possible in main menu, no access to root.

**Comment by DJ1TJOO** [comment]
> Not planning to add this rn, but could be a mod

The problem is mods don't have access to achievements

**Pull request closed without merging**
