### PR TITLE
Correcting spelling and translated missing section

### PR DESCRIPTION
**Pull request by EnderDoom77**
Added many missing accent marks (´)
Translated the "Rotation by building Type" section.

### CODE REVIEW

**Comment by tobspr** [comment]
There are merge conflicts, could you have a look? :)

**Comment by EnderDoom77** [comment]
The four merge conflicts have been looked at and resolved.

**Comment by EnderDoom77** [comment]
I'm unsure why the merge conflict even appeared and now solving it is throwing an error on electron?

**Comment by tobspr** [comment]
TY!

**Pull request merged**
