### PR TITLE
Update base-nl.yaml

### PR DESCRIPTION
**Pull request by stormweb-dev**
New translation added

### CODE REVIEW

**Comment by DerFeldspatz** [comment]
Why did you delete one of the tooltips?

**Comment by DJ1TJOO** [comment]
> Why did you delete one of the tooltips?

I think they thought it was still double in the Dutch translation: https://github.com/tobspr/shapez.io/issues/1194

**Comment by DerFeldspatz** [comment]
I remember the tooltip for white color being double in both english and german translation with slightly different phrasing. So I think it's intended, no?

**Comment by DJ1TJOO** [comment]
> I remember the tooltip for white color being doubled in both english and german translation with slightly different phrasing. So I think it's intended, no?

It is intended, my phrasing was a little wrong

**Comment by tobspr** [comment]
Thanks!

**Pull request merged**
