### PR TITLE
Major ui changes

### PR DESCRIPTION
**Pull request by dengr1065**
- rewrote large parts of textual state css so it's better for desktops
- changed settings categories to be enum
- made settings really easier to navigate
- added logo to about the game page, so it looks more filled and cool
- replaced `github` with `GitHub` and `factorio` with `Factorio`
- also replaced all `discord` with `Discord` in translations where needed
- added firefox scrollbar coloring, because it annoyed me
- it's 9 am i don't remember anything anymore

### CODE REVIEW

**Comment by dengr1065** [comment]
Some cool screenshots
---
<table>
<tbody>
<tr>
<th>Dark</th>
<th>Light</th>
</tr>
<tr>
<td>changelog/dark</td>
<td>changelog/dark</td>
</tr>
<tr>
<td>changelog/dark</td>
<td>changelog/dark</td>
</tr>
<tr>
<td>changelog/dark</td>
<td>changelog/dark</td>
</tr>
</tbody>
</table>

**Comment by tobspr** [comment]
Uh, fancy! How does it look on smaller resolutions?

**Comment by dengr1065** [comment]
All textual states use `width`/`max-width` together, so it looks good on low-width (not mobile tho)

And, settings sidebar also has `min-width`.


Although, I didn't yet test it on Chromium. Will do now. (also I see merge conflict on translation, will fix that)

**Comment by dengr1065** [comment]
Alright i think that should work - syncTranslations with git is weird.

**Pull request merged**
