### PR TITLE
Added mod processing requirements

### PR DESCRIPTION
**Pull request by DJ1TJOO**
This mods adds a hook for custom processing requirements

### CODE REVIEW

**Comment by ZygZagGaming** [comment]
This PR doesn't modify the `canProcess` method in `item_processor.js`

**Comment by EmeraldBlock** [comment]
> This PR doesn't modify the `canProcess` method in `item_processor.js`

isn't this PR for whether a building can *accept* an item, not whether it's ready to perform processing? (though the naming is confusing)

**Comment by DJ1TJOO** [comment]
> > This PR doesn't modify the `canProcess` method in `item_processor.js`
> 
> isn't this PR for whether a building can _accept_ an item, not whether it's ready to perform processing? (though the naming is confusing)

It is for both. A process can only be done when there are items in the building. If you stop the accepting of the items the process wil also be stopped

**Comment by EmeraldBlock** [comment]
> > > This PR doesn't modify the `canProcess` method in `item_processor.js`
> > 
> > 
> > isn't this PR for whether a building can _accept_ an item, not whether it's ready to perform processing? (though the naming is confusing)
> 
> It is for both. A process can only be done when there are items in the building. If you stop the accepting of the items the process wil also be stopped

yeah, that's what I mean - *directly*, it's only about accepting the item (and it also means it can't do fancier processing requirements)

**Comment by ZygZagGaming** [comment]
What I'm saying is that `canProcess` checks requirements separately and it needs to return true for mod processors to function

**Comment by EmeraldBlock** [comment]
> What I'm saying is that `canProcess` checks requirements separately and it needs to return true for mod processors to function

By default, it simply checks that an item has been accepted in every slot. Filtering items is done when accepting, not processing.

**Pull request merged**
