### PR TITLE
Update base-de.yaml translation

### PR DESCRIPTION
**Pull request by DerFeldspatz**
Finish most of the translation and correct some typos/grammar. Checked for some inconsistencies in syntax. It accidentally tries to delete lines 155+156 and i can't figure out how to change this >.<
Can you please take this one change out?

### CODE REVIEW

**Comment by tobspr** [comment]
Sehr cool, danke!

**Comment by tobspr** [comment]
(Behebe das mit den Zeilen im nachhinein)

**Comment by dengr1065** [comment]
did you forget the language again? :smile:

**Comment by DerFeldspatz** [comment]
What do you mean? 😅

**Comment by dengr1065** [comment]
international repo = english language for issues and pull reqs, it's kinda annoying but fun to see a german response for english comment

**Pull request merged**
