### PR TITLE
Corrects "20 Upgrade Tiers" to "∞ Upgrade Tiers" across most languages

### LINKED ISSUE #854: Upgrade to standalone prompt incorrectly states "20 UPGRADE TIERS"
Actual value is 1000.

### PR DESCRIPTION
**Pull request by Hyperion-21**
Fixes #854 

Steam page translations other than English, and all languages except Spanish, French, Japanese, Korean, both Portugueses, and Simplified Chinese, weren't changed.

### CODE REVIEW

**Comment by Galo223344** [comment]
I have now changed from "20 upgrade tiers" to "infinite upgrade tiers" in the pr for the spanish translation 👍

**Comment by Hyperion-21** [comment]
> I have now changed from "20 upgrade tiers" to "infinite upgrade tiers" in the pr for the spanish translation

It would be preferable if you made a PR onto the `fix-upgradeprompt-levels` branch on my fork

**Comment by Galo223344** [comment]
That's not the only change I made in my PR tho (#875). I've also translated the rest of the strings and corrected some mistakes.
Also, i'm not very familiar with GitHub so correct me if i'm wrong, but if your PR gets merged (With the changes in base-es), wouldn't it override_the changes I made in my PR?

**Comment by EmeraldBlock** [comment]
I believe that if your spanish translation gets merged, then Hyperion's correction gets merged, there will be a merge conflict between the two (which can be easily fixed). I would recommend translating it with "infinite" so that you don't have to do it after Hyperion's correction is merged.

also @Hyperion-21 you might not want to remove the bold tags for the English translation

**Comment by Hyperion-21** [comment]
@EmeraldBlock "Unlimited Savegames" and "Unlimited Markers" don't have bold tags, so why should "Unlimited Upgrade Tiers?"

**Comment by EmeraldBlock** [comment]
All translations are supposed to have the same tags in the same order (syncTranslations also checks for that). And anyway, although it is weird that the bold stops halfway through, the "Unlimited Upgrade Tiers" line is surrounded by bold.

**Pull request closed without merging**
